Create LICENSE.md
dtinth/WebMIDICon pull request #77
Opened 2022-10-19 17:44 UTC by Badal-05

Created License.

2022-10-20 13:53 UTC, Badal-05 commented
Hi, could you please accept my work.

2022-10-20 14:40 UTC, dtinth requested changes

2022-10-20 14:40 UTC, dtinth commented on LICENSE.md
> +Copyright (c) 2022 Badal-05
Please change that to my username 😂

2022-10-21 03:59 UTC, Badal-05 commented
Sorry, I could not get your. Where should I add your username???

On Thu, Oct 20, 2022, 20:10 Thai Pangsakulyanont ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In LICENSE.md
> <https://github.com/dtinth/WebMIDICon/pull/77#discussion_r1000729031>:
>
> > @@ -0,0 +1,21 @@
>
> +MIT License
>
> +
>
> +Copyright (c) 2022 Badal-05
>
>
> Please change that to my username 😂
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dtinth/WebMIDICon/pull/77#pullrequestreview-1149396937>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A2KN7KLDZ6PFSXB64VTJNTTWEFKVHANCNFSM6AAAAAARJLOTYM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-10-21 05:12 UTC, closed without merging